#服务器断口
server:
  port: 8080
#MP配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#      table-prefix: tbl_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis-plule数据配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.1.5:3306/springboot?serverTimezone=UTC
      url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
      username: admin
      password: 111111